- hosts: /inventory/static_hosts
  connection: local
  gather_facts: False
  pre_tasks:
    - include_vars: ../variables/ec2_linux_users.yml

  tasks:
    - name: download custom artifact from s3
      shell:
        "aws s3 cp s3://ci-build-artifacts/Infocyte/Infocyte_RtsLinux32/{{artifact_build_no}}/rts.linux32.exe /agent  --profile profilename"