---
### provision AWS EC2 instance
- hosts: localhost
  connection: local
  gather_facts: False
  pre_tasks:
    - include_vars: /ansible_repo/prov_aws_ec2_ansible_2/variables/variable.yml
  tasks:
    - name: Provision {{ ec2_count }} instances 
      local_action:
        module: ec2
        key_name: "{{ ec2_keypair }}"
        group_id: "{{ ec2_security_group_id }}"
        instance_type: "{{ ec2_instance_type }}"
        image: "{{ ec2_image }}"
        vpc_subnet_id: "{{ ec2_subnet_id }}"
        region: "{{ ec2_region }}"
        instance_tags: '{"Type":"{{ec2_instance_type}}", "Role":"{{ec2_tag_Role}}"}'
        assign_public_ip: yes
        instance_profile_name: "{{iam_role}}"
        wait: true
        exact_count: "{{ ec2_count }}"
        count_tag:
          Role: "{{ ec2_tag_Role }}"
        volumes:
          - device_name: /dev/sda1
            volume_size: "{{ ec2_volume_size }}"
            delete_on_termination: true
      register: ec2

    - name: Wait for the instances to boot by checking the ssh port
      wait_for: host={{item.private_ip}} port=22 delay=15 timeout=300 state=started
      with_items: "{{ ec2.instances }}"

    - add_host:
        name: "{{item.public_dns_name }}"
        ec2_private_ip: "{{item.private_ip}}"
        groups: tag_Type_{{ec2_tag_Type}}
        ec2_region: "{{ ec2_region }}"
        ec2_tag_Type: "{{ ec2_tag_Type}}"
        ec2_tag_Role: "{{ ec2_tag_Role }}"
        ec2_public_ip_address: "{{ item.public_ip }}"
      with_items: "{{ ec2.instances }}"
  
  post_tasks:
    - name: add instance to inventory
      meta: refresh_inventory




