# linux-64-bit-provisioning
#
# VARIABLES EXPECTED @ RUNTIME:
#    - ec2 (desired instance name)


- hosts: localhost
  tasks:
    - name: Create ec2 instance from launch template
      ec2_instance:
        name: "{{ ec2_host }}"
        state: running
        vpc_subnet_id: subnet-0096d58f7a970cedb
        instance_type: t2.micro
        termination_protection: yes
        launch_template:
          id: lt-04eee55f795e1c15a
        region: us-east-1
        wait: yes
      register: ec2_results